### ISSUE TITLE
Shortcuts Plugins

### ISSUE THREAD

**Issue by melonamin** [swiftbar/SwiftBar#344]
## Shortcuts Plugins

Currently to create a plugin the user must have basic scripting\coding skills.
Implementing a new type of plugin - “Shortcut Plugin” - would allow users to create the plugins inside Shortcuts app, potentially expanding the user base.

## TODO:

- [X] Basic UI to add and delete plugins
- [X]  New plugin type "Shortcut", runs provided shortcut instead of a file based plugin
- [X]  Store Shortcut plugins in UserDefaults
- [X]  Make Shortcut plugin UI reactive
- [x] Enable\disable plugins
- ~~Plugin repository for Shortcuts Plugins~~ (maybe another day)
- [x]  Localization

## BETA
* [Beta 1](https://github.com/swiftbar/SwiftBar/releases/download/v1.5.0-beta-1/SwiftBar.v1.5.0.b469.zip)
* [Beta 2](https://github.com/swiftbar/SwiftBar/releases/download/v1.5.0-beta-2/SwiftBar.v1.5.0.b478.zip)

## Shortcut Examples
* [Fake Weather](https://www.icloud.com/shortcuts/7f2e81e6081245b59af1f8b0ed5c559d)
* [Featured image from Unsplash](https://www.icloud.com/shortcuts/be750380ad5c4848933771940c376934)

Adding Shortcuts Plugin Settings View:
<img width="818" alt="CleanShot 2022-11-08 at 16 01 34@2x" src="https://user-images.githubusercontent.com/222100/200674728-e98c809e-251c-471a-8ccf-04a6a9649cd1.png">

<img width="862" alt="CleanShot 2022-11-08 at 16 01 51@2x" src="https://user-images.githubusercontent.com/222100/200674731-6b380992-fe9c-4d42-b3a2-ccebb105c592.png">

**Comment by dchevell** [comment]
When I click "Add" under macOS Ventura (SwiftBar: 1.5.0 (478), macOS: 13.1 (22C65)) nothing appears and SwiftBar beachballs until I have to force quit. 

Just curious - is that expected, or can I provide any useful diagnostic data? Not bothered, but happy to test/troubleshoot if it's helpful.

**Comment by melonamin** [comment]
Hi @dchevell,

sorry, for some reason I missed the notification about your comment from GitHub... :(

Can you please try this build? If you see the beach ball, can you get the logs from Console.app (Search = "process == SwiftBar")

[SwiftBar.app.zip](https://github.com/swiftbar/SwiftBar/files/11237377/SwiftBar.app.zip)

**Comment by dchevell** [comment]
@melonamin no need to apologise, I'm grateful for your work on this app :) 

Still beachballed for me on this build. I reproduced before installing (b479), and after (confirmed b494).


Console logs - I clicked "Add" at `09:17:00.567184+1000`.

```default	09:16:45.994402+1000	SwiftBar	LSExceptions shared instance invalidated for timeout.
default	09:16:46.884279+1000	SwiftBar	order window front conditionally: cc1 related: 0
default	09:17:00.000746+1000	SwiftBar	Requesting manual refresh for plugin id: batterystatus.sh type: Executable name: batterystatus path: /Users/dchevell/Library/Mobile Documents/com~apple~CloudDocs/SwiftBar/batterystatus.sh
default	09:17:00.000973+1000	SwiftBar	Refreshing plugin metadata /Users/dchevell/Library/Mobile Documents/com~apple~CloudDocs/SwiftBar/batterystatus.sh
default	09:17:00.179980+1000	SwiftBar	Successfully executed script /Users/dchevell/Library/Mobile Documents/com~apple~CloudDocs/SwiftBar/batterystatus.sh
default	09:17:00.567184+1000	SwiftBar	It's not legal to call -layoutSubtreeIfNeeded on a view which is already being laid out.  If you are implementing the view's -layout method, you can call -[super layout] instead. Break on void _NSDetectedLayoutRecursion(void) to debug.  This will be logged only once.  This may break in the future.
default	09:17:00.573292+1000	SwiftBar	order window front conditionally: cc1 related: 0
default	09:17:00.574995+1000	SwiftBar	order window: cc6 op: 1 relative: cc1 related: 0
default	09:17:00.838943+1000	SwiftBar	order window: cc6 op: 1 relative: cc1 related: 0
default	09:18:00.000260+1000	SwiftBar	Requesting manual refresh for plugin id: batterystatus.sh type: Executable name: batterystatus path: /Users/dchevell/Library/Mobile Documents/com~apple~CloudDocs/SwiftBar/batterystatus.sh
default	09:18:00.000361+1000	SwiftBar	Refreshing plugin metadata /Users/dchevell/Library/Mobile Documents/com~apple~CloudDocs/SwiftBar/batterystatus.sh
default	09:18:00.194951+1000	SwiftBar	Successfully executed script /Users/dchevell/Library/Mobile Documents/com~apple~CloudDocs/SwiftBar/batterystatus.sh
```

**Comment by melonamin** [comment]
Hmm… interesting, I need to look into it. 🤔

**Comment by melonamin** [comment]
Manged to reproduce it on my machine, which is very good, I'm getting closer

**Comment by melonamin** [comment]
@dchevell how about this one? [SwiftBar.app.zip](https://github.com/swiftbar/SwiftBar/files/11276357/SwiftBar.app.zip)

**Comment by dchevell** [comment]
Same thing I'm afraid @melonamin . Confirmed b495 in the about screen, then captured these logs:

```
default	06:56:46.238645+1000	SwiftBar	It's not legal to call -layoutSubtreeIfNeeded on a view which is already being laid out.  If you are implementing the view's -layout method, you can call -[super layout] instead. Break on void _NSDetectedLayoutRecursion(void) to debug.  This will be logged only once.  This may break in the future.
default	06:56:46.244944+1000	SwiftBar	order window front conditionally: fea8 related: 0
default	06:56:46.246529+1000	SwiftBar	order window: feb5 op: 1 relative: fea8 related: 0
default	06:56:46.509324+1000	SwiftBar	order window: feb5 op: 1 relative: fea8 related: 0
```

(One other odd side effect: On prior builds, the `sfcolor` parameter would only apply to inline symbols, e.g. `:circle: | sfcolor=green sfimage=square` would make the inline `:circle:` green, but _not_ affect the sfimage icon placed to the left. On this build, the colour gets applied to both, which made one of my scripts that uses a lot of colour based info kinda weird)

**Comment by melonamin** [comment]
@dchevell  I have a good feeling about this build, can you please try?
[SwiftBar.app.zip](https://github.com/swiftbar/SwiftBar/files/11585795/SwiftBar.app.zip)

**Comment by melonamin** [comment]
@space-esquire you've tried the latest one I [linked](https://github.com/swiftbar/SwiftBar/issues/344#issuecomment-1566262940), correct?

**Comment by melonamin** [comment]
FML then! 🥲

**Comment by dchevell** [comment]
@melonamin I can't speak for anyone else, but this build finally works for me. Was able to add a shortcut plugin with no errors, and it all seems to work. 

A little weirdness where, after adding one, I can't click on it to highlight or delete - but if I switch to another tab (e.g. Code Plugins) then back to Shortcut Plugins, it resolves that issue.

**Comment by melonamin** [comment]
That’s awesome to hear, thanks! I’ll check the selection\highlight issue
